/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package knugra.server.java;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
    }
}
